### ISSUE TITLE
Duplicate Object; was "Final Object Deletion"

### ISSUE THREAD

**Issue by gdemme** [dfki-asr/compass#7] opened 2015-04-01 09:16 UTC
Description:
Deleting the only Scene Node, delete the scene node from the object list, but not from 3D view. Reloading the project fixes this. Sometimes it works properly…

Reconstruction:
– Start with empty scene
– Add an object
– Delete the object: object stays visible in 3D

**Comment by wherget** [comment] 2015-04-01 19:34
The behavoiur you see, especially it not occuring deterministically, suggests that the issue is due to our implementation of transactions when working with the database layer. It would be most helpful if you could provide a snippet of your container log from the time when this behaviour occured, which would allow us to narrow down the exact cause. Especially look for log entries from exceptions.

If you're lucky, then the bug you're seeing is one of those we're currently fixing.

**Comment by gdemme** [comment] 2015-04-27 10:51
I tried reproducing the bug. 

It seems, it is not a deletion bug. Do the following:
- Create an object (either from new scene node or prefab)
- Create a new prefab by dragging the object to the prefabs area
- This creates a duplicate of the original object. Check by moving the original object.

The duplicate does not appear in the object list, but it is selectable and cannot be deleted.
Reloading the scene removes the duplicate object.

**Comment by spidan** [comment] 2015-05-08 09:39
The problem actually originates from prefabs being SceneNodes, triggering the onSceneNodeCreated event when creating a prefab, which, in turn, causes the prefab to be converted to a group node in the xml3d tree.
Fixing this bug is a little tricky, though, as there is currently no easy and reliable way to determine whether a scene node is used as prefab on the time of its creation.

**Comment by wherget** [comment] 2015-05-08 10:01
Shouldn't the Prefab have `null` as a `parent` (seeing as it's not in the scene tree)? If that's indeed the case, the only other node where that condition applies, is the root scene node, which is known when such an event occurs.
Sounds quite fixable to me, then.

**Comment by wherget** [comment] 2015-11-20 12:32
This will land in 2.1.1, which I will start preparing now. Therefore, I'm closing this issue.

**Closed as completed by wherget** 2015-11-20 12:32 UTC
Labels: bug
